name: bpb
channels:
  - conda-forge
  - cswarth
  - defaults
dependencies:
  - ca-certificates=2016.9.26=0
  - cairo=1.14.6=0
  - certifi=2017.1.23=py27_0
  - fontconfig=2.11.1=6
  - freetype=2.6.3=1
  - gettext=0.19.7=1
  - glib=2.51.0=2
  - harfbuzz=1.3.4=0
  - icu=56.1=4
  - jellyfish=0.5.6=py27_0
  - jpeg=9b=0
  - libffi=3.2.1=3
  - libiconv=1.14=4
  - libpng=1.6.28=0
  - libtiff=4.0.6=7
  - libxml2=2.9.4=3
  - ncurses=5.9=10
  - nestly=0.6=py27_0
  - openssl=1.0.2h=3
  - pango=1.40.3=0
  - pcre=8.39=0
  - pip=9.0.1=py27_0
  - pixman=0.34.0=0
  - psutil=5.2.1=py27_0
  - pyqt=4.11.4=py27_2
  - python=2.7.12=1
  - qt=4.8.7=3
  - readline=6.2=0
  - setuptools=33.1.0=py27_0
  - sip=4.18=py27_1
  - sqlite=3.13.0=1
  - tk=8.5.19=1
  - wheel=0.29.0=py27_0
  - xvfbwrapper=0.2.8=py27_0
  - xz=5.2.2=0
  - zlib=1.2.11=0
  - pip:
    - absl-py==0.1.10
    - backports.weakref==1.0.post1
    - biopython==1.68
    - bleach==1.5.0
    - cycler==0.10.0
    - dendropy==3.12.3
    - distance==0.1.3
    - enum34==1.1.6
    - ete3==3.0.0b35
    - funcsigs==1.0.2
    - functools32==3.2.3.post2
    - futures==3.2.0
    - html5lib==0.9999999
    - markdown==2.6.11
    - matplotlib==2.0.0
    - mock==2.0.0
    - numpy==1.14.1
    - pandas==0.19.2
    - patsy==0.4.1
    - pbr==3.1.1
    - protobuf==3.5.1
    - pyerf==1.0.1
    - pygments==2.2.0
    - pyparsing==2.1.10
    - pysam==0.10.0
    - python-dateutil==2.6.0
    - pytz==2016.10
    - pyyaml==3.12
    - scikits.bootstrap==1.0.0
    - scipy==0.18.1
    - scons==2.5.1
    - seaborn==0.7.1
    - seqmagick==0.6.2
    - six==1.10.0
    - statsmodels==0.8.0
    - subprocess32==3.2.7
    - tensorflow==1.5.0
    - tensorflow-tensorboard==1.5.1
    - werkzeug==0.14.1
prefix: /opt/conda/envs/bpb

